// Generated by SolidPython 1.1.3 on 2025-04-12 11:14:56


difference() {
	union() {
		linear_extrude(height = 3) {
			polygon(points = [[0, 0], [80, 0], [40.0000000000, 69.2820323028]]);
		}
		union() {
			translate(v = [0.0000000000, 0.0000000000, 3.0]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [80.0000000000, 0.0000000000], [40.0000000000, 69.2820323028]]);
				}
			}
			translate(v = [2.0000000000, 1.0000000000, 4.631949047986203]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [76.0000000000, 0.0000000000], [38.0000000000, 65.8179306876]]);
				}
			}
			translate(v = [4.0000000000, 2.0000000000, 6.263898095972406]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [72.0000000000, 0.0000000000], [36.0000000000, 62.3538290725]]);
				}
			}
			translate(v = [6.0000000000, 3.0000000000, 7.895847143958609]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [68.0000000000, 0.0000000000], [34.0000000000, 58.8897274573]]);
				}
			}
			translate(v = [8.0000000000, 4.0000000000, 9.527796191944812]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [64.0000000000, 0.0000000000], [32.0000000000, 55.4256258422]]);
				}
			}
			translate(v = [10.0000000000, 5.0000000000, 11.159745239931016]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [60.0000000000, 0.0000000000], [30.0000000000, 51.9615242271]]);
				}
			}
			translate(v = [12.0000000000, 6.0000000000, 12.791694287917219]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [56.0000000000, 0.0000000000], [28.0000000000, 48.4974226119]]);
				}
			}
			translate(v = [14.0000000000, 7.0000000000, 14.423643335903423]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [52.0000000000, 0.0000000000], [26.0000000000, 45.0333209968]]);
				}
			}
			translate(v = [16.0000000000, 8.0000000000, 16.055592383889625]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [48.0000000000, 0.0000000000], [24.0000000000, 41.5692193817]]);
				}
			}
			translate(v = [18.0000000000, 9.0000000000, 17.68754143187583]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [44.0000000000, 0.0000000000], [22.0000000000, 38.1051177665]]);
				}
			}
			translate(v = [20.0000000000, 10.0000000000, 19.319490479862033]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [40.0000000000, 0.0000000000], [20.0000000000, 34.6410161514]]);
				}
			}
			translate(v = [22.0000000000, 11.0000000000, 20.951439527848237]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [36.0000000000, 0.0000000000], [18.0000000000, 31.1769145362]]);
				}
			}
			translate(v = [24.0000000000, 12.0000000000, 22.583388575834437]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [32.0000000000, 0.0000000000], [16.0000000000, 27.7128129211]]);
				}
			}
			translate(v = [26.0000000000, 13.0000000000, 24.215337623820645]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [28.0000000000, 0.0000000000], [14.0000000000, 24.2487113060]]);
				}
			}
			translate(v = [28.0000000000, 14.0000000000, 25.847286671806845]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [24.0000000000, 0.0000000000], [12.0000000000, 20.7846096908]]);
				}
			}
			translate(v = [30.0000000000, 15.0000000000, 27.47923571979305]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [20.0000000000, 0.0000000000], [10.0000000000, 17.3205080757]]);
				}
			}
			translate(v = [32.0000000000, 16.0000000000, 29.111184767779253]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [16.0000000000, 0.0000000000], [8.0000000000, 13.8564064606]]);
				}
			}
			translate(v = [34.0000000000, 17.0000000000, 30.743133815765454]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [12.0000000000, 0.0000000000], [6.0000000000, 10.3923048454]]);
				}
			}
			translate(v = [36.0000000000, 18.0000000000, 32.37508286375166]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [8.0000000000, 0.0000000000], [4.0000000000, 6.9282032303]]);
				}
			}
			translate(v = [38.0000000000, 19.0000000000, 34.00703191173786]) {
				linear_extrude(height = 1.6319490479862033) {
					polygon(points = [[0.0000000000, 0.0000000000], [4.0000000000, 0.0000000000], [2.0000000000, 3.4641016151]]);
				}
			}
		}
	}
	translate(v = [40.0000000000, 23.0940107676, -2]) {
		linear_extrude(height = 2) {
			text(halign = "center", size = 8, text = "TEST", valign = "center");
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
#!/usr/bin/env python3
"""
Improved 3D Model Generation Module for Crazy Stock Badges Project

This module provides classes and functions for generating 3D models from stock data
using SolidPython to create OpenSCAD files that can be rendered to STL for 3D printing.
"""

import os
import numpy as np
import pandas as pd
from solid import *
from solid.utils import *
import logging
from abc import ABC, abstractmethod
from pathlib import Path
import math

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('improved_3d_models')


class StockDataValidator:
    """Validates and preprocesses stock data for 3D model generation."""
    
    @staticmethod
    def validate_data(data):
        """
        Validate that the data contains the required columns.
        
        Args:
            data (pandas.DataFrame): Stock data
            
        Returns:
            bool: True if data is valid, False otherwise
        """
        required_columns = ['Close', 'Volume']
        
        if not isinstance(data, pd.DataFrame):
            logger.error("Data must be a pandas DataFrame")
            return False
        
        for col in required_columns:
            if col not in data.columns:
                logger.error(f"Required column '{col}' not found in data")
                return False
        
        if len(data) < 5:
            logger.error("Data must contain at least 5 rows")
            return False
            
        return True
    
    @staticmethod
    def normalize_data(data, columns=None, new_min=0, new_max=10):
        """
        Normalize specified columns to a new range.
        
        Args:
            data (pandas.DataFrame): Stock data
            columns (list): List of columns to normalize
            new_min (float): Minimum value for normalized data
            new_max (float): Maximum value for normalized data
            
        Returns:
            pandas.DataFrame: Data with normalized columns added
        """
        if columns is None:
            columns = ['Close', 'Volume']
        
        result = data.copy()
        
        for col in columns:
            if col in data.columns:
                norm_col = f'{col}_Normalized'
                min_val = data[col].min()
                max_val = data[col].max()
                
                # Avoid division by zero
                if max_val == min_val:
                    result[norm_col] = new_min
                else:
                    result[norm_col] = (data[col] - min_val) / (max_val - min_val) * (new_max - new_min) + new_min
            else:
                logger.warning(f"Column '{col}' not found in data, skipping normalization")
        
        return result


class Badge3DModel(ABC):
    """Abstract base class for 3D badge models."""
    
    def __init__(self, stock_data, ticker_symbol, params=None):
        """
        Initialize the 3D model.
        
        Args:
            stock_data (pandas.DataFrame): Stock data
            ticker_symbol (str): Stock ticker symbol
            params (dict): Additional parameters for the model
        """
        self.ticker_symbol = ticker_symbol
        self.params = params or {}
        
        # Validate and normalize data
        validator = StockDataValidator()
        if not validator.validate_data(stock_data):
            raise ValueError("Invalid stock data")
        
        # Set default normalization ranges
        height_range = self.params.get('height_range', (0, 15))
        width_range = self.params.get('width_range', (0, 10))
        
        # Normalize data
        self.data = validator.normalize_data(
            stock_data, 
            columns=['Close', 'Volume', 'High', 'Low'],
            new_min=height_range[0],
            new_max=height_range[1]
        )
        
        # Normalize volume separately for width
        self.data['Volume_Width'] = validator.normalize_data(
            stock_data, 
            columns=['Volume'],
            new_min=width_range[0],
            new_max=width_range[1]
        )['Volume_Normalized']
        
        # Initialize model components
        self.base_model = None
        self.feature_model = None
        self.text_model = None
        self.final_model = None
        
        # Model statistics
        self.stats = {
            'num_objects': 0,
            'height_diff': 0,
            'width_diff': 0,
            'depth_diff': 0,
            'size': (0, 0, 0)
        }
    
    @abstractmethod
    def generate_base(self):
        """Generate the base part of the model."""
        pass
    
    @abstractmethod
    def generate_feature(self):
        """Generate the feature part of the model based on stock data."""
        pass
    
    @abstractmethod
    def generate_text(self):
        """Generate text elements for the model."""
        pass
    
    def combine_models(self):
        """
        Combine base, feature, and text models into the final model.
        
        Returns:
            solid.OpenSCADObject: Combined 3D model
        """
        if self.base_model is None:
            self.generate_base()
        
        if self.feature_model is None:
            self.generate_feature()
        
        if self.text_model is None:
            self.generate_text()
        
        # Combine models
        combined = union()(
            self.base_model,
            self.feature_model
        )
        
        # Apply text as a difference (engraving)
        if self.text_model is not None:
            self.final_model = difference()(
                combined,
                self.text_model
            )
        else:
            self.final_model = combined
        
        return self.final_model
    
    def calculate_stats(self):
        """
        Calculate statistics about the model.
        
        Returns:
            dict: Model statistics
        """
        # This is a placeholder - in a real implementation, we would
        # analyze the OpenSCAD model to extract these statistics
        self.stats['num_objects'] = len(self.data)
        self.stats['height_diff'] = self.params.get('height_range', (0, 15))[1]
        self.stats['width_diff'] = self.params.get('width_range', (0, 10))[1]
        self.stats['depth_diff'] = 5  # Example value
        self.stats['size'] = (100, 100, 20)  # Example values
        
        return self.stats
    
    def save_to_file(self, filename=None):
        """
        Save the model to an OpenSCAD file.
        
        Args:
            filename (str): Output filename
            
        Returns:
            str: Path to the saved file
        """
        if self.final_model is None:
            self.combine_models()
        
        if filename is None:
            filename = f"{self.ticker_symbol}_badge.scad"
        
        # Save the model
        scad_render_to_file(self.final_model, filename)
        logger.info(f"Model saved to {filename}")
        
        return filename


class DiscBadge(Badge3DModel):
    """Circular badge with stock data features."""
    
    def generate_base(self):
        """
        Generate a circular base for the badge.
        
        Returns:
            solid.OpenSCADObject: Base 3D model
        """
        radius = self.params.get('base_radius', 50)
        height = self.params.get('base_height', 3)
        
        self.base_model = cylinder(r=radius, h=height, center=False)
        return self.base_model
    
    def generate_feature(self):
        """
        Generate features on the badge based on stock data.
        
        Returns:
            solid.OpenSCADObject: Feature 3D model
        """
        feature_type = self.params.get('feature_type', 'jagged_edge')
        
        if feature_type == 'jagged_edge':
            self.feature_model = self._generate_jagged_edge()
        elif feature_type == 'spiral':
            self.feature_model = self._generate_spiral()
        else:
            logger.warning(f"Unknown feature type: {feature_type}, using jagged_edge")
            self.feature_model = self._generate_jagged_edge()
        
        return self.feature_model
    
    def _generate_jagged_edge(self):
        """
        Generate a jagged edge disc based on stock prices.
        
        Returns:
            solid.OpenSCADObject: Jagged edge 3D model
        """
        base_radius = self.params.get('base_radius', 50)
        height = self.params.get('feature_height', 2)
        z_offset = self.params.get('base_height', 3)
        
        # Parameters for the polygon
        num_points = len(self.data)  # Use all data points
        angles = np.linspace(0, 2 * np.pi, num_points)  # Angles around the circle
        
        # Map normalized stock prices to the polygon edge
        radii = self.data['Close_Normalized'] + base_radius
        
        # Create points for the polygon
        points = []
        for i in range(num_points):
            x = radii.iloc[i] * np.cos(angles[i])  # X coordinate
            y = radii.iloc[i] * np.sin(angles[i])  # Y coordinate
            points.append([x, y])
        
        # Create 2D polygon and extrude to 3D
        jagged_disc_2d = polygon(points)
        jagged_disc_3d = linear_extrude(height=height)(jagged_disc_2d)
        
        # Translate to sit on top of the base
        return translate([0, 0, z_offset])(jagged_disc_3d)
    
    def _generate_spiral(self):
        """
        Generate a spiral landscape based on stock data.
        
        Returns:
            solid.OpenSCADObject: Spiral landscape 3D model
        """
        radius = self.params.get('spiral_radius', 45)
        z_offset = self.params.get('base_height', 3)
        spiral_turns = self.params.get('spiral_turns', 7)
        
        # Generate points on a spiral
        num_points = len(self.data)
        angles = np.linspace(0, spiral_turns * 2 * np.pi, num_points)  # Spiral angles
        radii = np.linspace(0, radius, num_points)  # Gradually increase radius for spiral
        
        # Map normalized stock prices to heights and widths
        heights = self.data['Close_Normalized']
        widths = self.data['Volume_Width']
        
        # Calculate coordinates
        x = radii * np.cos(angles)  # X coordinates
        y = radii * np.sin(angles)  # Y coordinates
        
        # Create the landscape as a series of stacked cylinders
        landscape = []
        for i in range(num_points):
            cylinder_height = heights.iloc[i]
            cylinder_radius = widths.iloc[i]
            
            landscape.append(
                translate([x[i], y[i], z_offset])(
                    cylinder(r=cylinder_radius, h=cylinder_height, center=False)
                )
            )
        
        # Combine the landscape into a single object
        return union()(landscape)
    
    def generate_text(self):
        """
        Generate text for the badge.
        
        Returns:
            solid.OpenSCADObject: Text 3D model
        """
        text_depth = self.params.get('text_depth', 2)
        text_size = self.params.get('text_size', 10)
        text_content = self.params.get('text_content', self.ticker_symbol)
        text_position = self.params.get('text_position', 'bottom')
        
        # Create text object
        if len(text_content) > 10:
            # For longer text, use multiline
            self.text_model = self._generate_multiline_text(
                text_content, text_size, text_depth
            )
        else:
            # For shorter text, use single line
            text_2d = text(text_content, size=text_size, halign='center', valign='center')
            self.text_model = linear_extrude(height=text_depth)(text_2d)
        
        # Position the text
        if text_position == 'bottom':
            # Position text on the bottom of the badge (as an engraving)
            z_pos = -text_depth
            self.text_model = translate([0, 0, z_pos])(self.text_model)
        elif text_position == 'top':
            # Position text on the top of the badge
            base_height = self.params.get('base_height', 3)
            feature_height = self.params.get('feature_height', 2)
            z_pos = base_height + feature_height
            self.text_model = translate([0, 0, z_pos])(self.text_model)
        
        return self.text_model
    
    def _generate_multiline_text(self, text_content, size, depth, wrap_chars=10):
        """
        Generate multiline text object.
        
        Args:
            text_content (str): Text to display
            size (float): Text size
            depth (float): Text depth
            wrap_chars (int): Number of characters per line
            
        Returns:
            solid.OpenSCADObject: Multiline text 3D model
        """
        # Split text into lines
        lines = [text_content[i:i+wrap_chars] for i in range(0, len(text_content), wrap_chars)]
        num_lines = len(lines)
        
        # Generate 3D text objects for each line and center them
        text_objects = []
        line_spacing = size * 1.2  # Adjust spacing based on text size
        
        for i, line in enumerate(lines):
            y_offset = (num_lines - 1) / 2 - i  # Center the text block
            text_2d = text(line, size=size, halign='center', valign='center')
            text_3d = linear_extrude(height=depth)(text_2d)
            text_objects.append(translate([0, y_offset * line_spacing, 0])(text_3d))
        
        return union()(text_objects)


class RectangularBadge(Badge3DModel):
    """Rectangular badge with stock data features."""
    
    def generate_base(self):
        """
        Generate a rectangular base for the badge.
        
        Returns:
            solid.OpenSCADObject: Base 3D model
        """
        width = self.params.get('base_width', 100)
        depth = self.params.get('base_depth', 60)
        height = self.params.get('base_height', 3)
        
        self.base_model = cube([width, depth, height], center=False)
        return self.base_model
    
    def generate_feature(self):
        """
        Generate features on the badge based on stock data.
        
        Returns:
            solid.OpenSCADObject: Feature 3D model
        """
        feature_type = self.params.get('feature_type', 'bar_chart')
        
        if feature_type == 'bar_chart':
            self.feature_model = self._generate_bar_chart()
        elif feature_type == 'surface_plot':
            self.feature_model = self._generate_surface_plot()
        else:
            logger.warning(f"Unknown feature type: {feature_type}, using bar_chart")
            self.feature_model = self._generate_bar_chart()
        
        return self.feature_model
    
    def _generate_bar_chart(self):
        """
        Generate a bar chart based on stock prices.
        
        Returns:
            solid.OpenSCADObject: Bar chart 3D model
        """
        base_width = self.params.get('base_width', 100)
        base_depth = self.params.get('base_depth', 60)
        z_offset = self.params.get('base_height', 3)
        bar_width = base_width / len(self.data)
        
        # Create bars for each data point
        bars = []
        for i in range(len(self.data)):
            bar_height = self.data['Close_Normalized'].iloc[i]
            bar_depth = base_depth * 0.8  # Make bars slightly narrower than the base
            
            # Position each bar along the x-axis
            x_pos = i * bar_width
            y_pos = (base_depth - bar_depth) / 2  # Center bars on the y-axis
            
            bars.append(
                translate([x_pos, y_pos, z_offset])(
                    cube([bar_width * 0.9, bar_depth, bar_height])
                )
            )
        
        return union()(bars)
    
    def _generate_surface_plot(self):
        """
        Generate a surface plot based on stock data.
        
        Returns:
            solid.OpenSCADObject: Surface plot 3D model
        """
        base_width = self.params.get('base_width', 100)
        base_depth = self.params.get('base_depth', 60)
        z_offset = self.params.get('base_height', 3)
        
        # Create a grid of points
        grid_size = int(math.sqrt(len(self.data)))
        if grid_size < 2:
            grid_size = 2
        
        # Truncate data to fit grid
        data_points = min(grid_size * grid_size, len(self.data))
        heights = self.data['Close_Normalized'].iloc[:data_points].values
        
        # Reshape to grid
        try:
            height_grid = heights[:grid_size * grid_size].reshape(grid_size, grid_size)
        except ValueError:
            # If reshaping fails, pad with zeros
            padded = np.zeros(grid_size * grid_size)
            padded[:len(heights)] = heights
            height_grid = padded.reshape(grid_size, grid_size)
        
        # Calculate cell dimensions
        cell_width = base_width / grid_size
        cell_depth = base_depth / grid_size
        
        # Create cells for the surface
        cells = []
        for i in range(grid_size):
            for j in range(grid_size):
                cell_height = height_grid[i, j]
                
                x_pos = i * cell_width
                y_pos = j * cell_depth
                
                cells.append(
                    translate([x_pos, y_pos, z_offset])(
                        cube([cell_width * 0.95, cell_depth * 0.95, cell_height])
                    )
                )
        
        return union()(cells)
    
    def generate_text(self):
        """
        Generate text for the badge.
        
        Returns:
            solid.OpenSCADObject: Text 3D model
        """
        text_depth = self.params.get('text_depth', 2)
        text_size = self.params.get('text_size', 10)
        text_content = self.params.get('text_content', self.ticker_symbol)
        text_position = self.params.get('text_position', 'bottom')
        
        base_width = self.params.get('base_width', 100)
        base_depth = self.params.get('base_depth', 60)
        
        # Create text object
        text_2d = text(text_content, size=text_size, halign='center', valign='center')
        self.text_model = linear_extrude(height=text_depth)(text_2d)
        
        # Position the text
        x_pos = base_width / 2  # Center on x-axis
        y_pos = base_depth / 2  # Center on y-axis
        
        if text_position == 'bottom':
            # Position text on the bottom of the badge (as an engraving)
            z_pos = -text_depth
            self.text_model = translate([x_pos, y_pos, z_pos])(self.text_model)
        elif text_position == 'top':
            # Position text on the top of the badge
            base_height = self.params.get('base_height', 3)
            feature_height = self.params.get('feature_height', 10)  # Approximate
            z_pos = base_height + feature_height
            self.text_model = translate([x_pos, y_pos, z_pos])(self.text_model)
        elif text_position == 'front':
            # Position text on the front of the badge
            z_pos = self.params.get('base_height', 3) / 2
            y_pos = 0  # Front edge
            self.text_model = translate([x_pos, y_pos, z_pos])(
                rotate([90, 0, 0])(self.text_model)
            )
        
        return self.text_model


class TriangularBadge(Badge3DModel):
    """Triangular badge with stock data features."""
    
    def generate_base(self):
        """
        Generate a triangular base for the badge.
        
        Returns:
            solid.OpenSCADObject: Base 3D model
        """
        side_length = self.params.get('side_length', 80)
        height = self.params.get('base_height', 3)
        
        # Create an equilateral triangle
        points = [
            [0, 0],
            [side_length, 0],
            [side_length / 2, side_length * math.sin(math.radians(60))]
        ]
        
        triangle_2d = polygon(points)
        self.base_model = linear_extrude(height=height)(triangle_2d)
        return self.base_model
    
    def generate_feature(self):
        """
        Generate features on the badge based on stock data.
        
        Returns:
            solid.OpenSCADObject: Feature 3D model
        """
        feature_type = self.params.get('feature_type', 'pyramid')
        
        if feature_type == 'pyramid':
            self.feature_model = self._generate_pyramid()
        elif feature_type == 'terrain':
            self.feature_model = self._generate_terrain()
        else:
            logger.warning(f"Unknown feature type: {feature_type}, using pyramid")
            self.feature_model = self._generate_pyramid()
        
        return self.feature_model
    
    def _generate_pyramid(self):
        """
        Generate a pyramid feature with height based on stock data.
        
        Returns:
            solid.OpenSCADObject: Pyramid 3D model
        """
        side_length = self.params.get('side_length', 80)
        z_offset = self.params.get('base_height', 3)
        
        # Use the average of normalized close prices for the pyramid height
        pyramid_height = self.data['Close_Normalized'].mean() * 3
        
        # Create a pyramid (triangular prism)
        points = [
            [0, 0],
            [side_length, 0],
            [side_length / 2, side_length * math.sin(math.radians(60))]
        ]
        
        # Create the pyramid by scaling a series of triangles
        layers = 20  # Number of layers in the pyramid
        pyramid_parts = []
        
        for i in range(layers):
            # Calculate the scale factor for this layer
            scale_factor = 1.0 - (i / layers)
            layer_height = pyramid_height * (i / layers)
            
            # Scale the points for this layer
            scaled_points = [[p[0] * scale_factor, p[1] * scale_factor] for p in points]
            
            # Create the layer
            layer_2d = polygon(scaled_points)
            layer_3d = linear_extrude(height=pyramid_height/layers)(layer_2d)
            
            # Position the layer
            pyramid_parts.append(
                translate([
                    side_length * (1 - scale_factor) / 2,  # Center on x
                    side_length * (1 - scale_factor) / 4,  # Center on y
                    z_offset + layer_height
                ])(layer_3d)
            )
        
        return union()(pyramid_parts)
    
    def _generate_terrain(self):
        """
        Generate a terrain feature based on stock data.
        
        Returns:
            solid.OpenSCADObject: Terrain 3D model
        """
        side_length = self.params.get('side_length', 80)
        z_offset = self.params.get('base_height', 3)
        
        # Create a triangular grid
        grid_size = 10  # Number of divisions along each side
        
        # Calculate the height of the triangle
        triangle_height = side_length * math.sin(math.radians(60))
        
        # Calculate cell dimensions
        cell_width = side_length / grid_size
        cell_height = triangle_height / grid_size
        
        # Create cells for the terrain
        cells = []
        
        # Use stock data to determine cell heights
        # We'll cycle through the data if we need more points than we have
        data_len = len(self.data)
        
        cell_count = 0
        for i in range(grid_size):
            # Calculate the number of cells in this row
            row_cells = grid_size - i
            
            for j in range(row_cells):
                # Get the data index, cycling if necessary
                data_idx = cell_count % data_len
                cell_count += 1
                
                # Get the height for this cell
                terrain_height = self.data['Close_Normalized'].iloc[data_idx]
                
                # Calculate position
                x_pos = j * cell_width + (i * cell_width / 2)  # Offset each row
                y_pos = i * cell_height
                
                cells.append(
                    translate([x_pos, y_pos, z_offset])(
                        cube([cell_width * 0.95, cell_height * 0.95, terrain_height])
                    )
                )
        
        return union()(cells)
    
    def generate_text(self):
        """
        Generate text for the badge.
        
        Returns:
            solid.OpenSCADObject: Text 3D model
        """
        text_depth = self.params.get('text_depth', 2)
        text_size = self.params.get('text_size', 8)
        text_content = self.params.get('text_content', self.ticker_symbol)
        text_position = self.params.get('text_position', 'bottom')
        
        side_length = self.params.get('side_length', 80)
        
        # Create text object
        text_2d = text(text_content, size=text_size, halign='center', valign='center')
        self.text_model = linear_extrude(height=text_depth)(text_2d)
        
        # Position the text
        x_pos = side_length / 2  # Center on x-axis
        y_pos = side_length * math.sin(math.radians(60)) / 3  # Lower third of triangle
        
        if text_position == 'bottom':
            # Position text on the bottom of the badge (as an engraving)
            z_pos = -text_depth
            self.text_model = translate([x_pos, y_pos, z_pos])(self.text_model)
        elif text_position == 'top':
            # Position text on the top of the badge
            base_height = self.params.get('base_height', 3)
            feature_height = self.params.get('feature_height', 10)  # Approximate
            z_pos = base_height + feature_height
            self.text_model = translate([x_pos, y_pos, z_pos])(self.text_model)
        
        return self.text_model


class BadgeFactory:
    """Factory class for creating different types of badges."""
    
    @staticmethod
    def create_badge(badge_type, stock_data, ticker_symbol, params=None):
        """
        Create a badge of the specified type.
        
        Args:
            badge_type (str): Type of badge to create
            stock_data (pandas.DataFrame): Stock data
            ticker_symbol (str): Stock ticker symbol
            params (dict): Additional parameters for the badge
            
        Returns:
            Badge3DModel: Badge model instance
        """
        if badge_type == 'disc':
            return DiscBadge(stock_data, ticker_symbol, params)
        elif badge_type == 'rectangular':
            return RectangularBadge(stock_data, ticker_symbol, params)
        elif badge_type == 'triangular':
            return TriangularBadge(stock_data, ticker_symbol, params)
        else:
            logger.warning(f"Unknown badge type: {badge_type}, using disc")
            return DiscBadge(stock_data, ticker_symbol, params)


def main():
    """
    Main function for testing the module.
    """
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate 3D badge models from stock data')
    parser.add_argument('--ticker', type=str, default='TSLA', help='Stock ticker symbol')
    parser.add_argument('--data-file', type=str, default='./stock_data', help='Stock data CSV file')
    parser.add_argument('--badge-type', type=str, default='disc', 
                       choices=['disc', 'rectangular', 'triangular'], help='Badge type')
    parser.add_argument('--feature-type', type=str, help='Feature type (depends on badge type)')
    parser.add_argument('--output', type=str, help='Output file name')
    args = parser.parse_args()
    
    try:
        # Load stock data
        if os.path.exists(args.data_file):
            stock_data = pd.read_csv(args.data_file)
            logger.info(f"Loaded stock data from {args.data_file}")
        else:
            logger.error(f"Data file not found: {args.data_file}")
            return 1
        
        # Set parameters based on badge type
        params = {}
        if args.feature_type:
            params['feature_type'] = args.feature_type
        
        # Create the badge
        badge = BadgeFactory.create_badge(args.badge_type, stock_data, args.ticker, params)
        
        # Generate the model
        badge.generate_base()
        badge.generate_feature()
        badge.generate_text()
        badge.combine_models()
        
        # Calculate and print statistics
        stats = badge.calculate_stats()
        print("\nModel Statistics:")
        for key, value in stats.items():
            print(f"  {key}: {value}")
        
        # Save the model
        output_file = args.output or f"{args.ticker}_{args.badge_type}_badge.scad"
        badge.save_to_file(output_file)
        print(f"\nModel saved to: {output_file}")
        
    except Exception as e:
        logger.error(f"Error in main function: {e}")
        print(f"Error: {str(e)}")
        return 1
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
 
 
************************************************/
